# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-17 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildingName', models.CharField(max_length=255)),
                ('officeRoom', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealCardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CardType', models.CharField(max_length=255)),
                ('CardAmt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plateNo', models.CharField(max_length=255)),
                ('permitNo', models.CharField(max_length=255)),
                ('dateExpiry', models.DateTimeField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campusID', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('firstName', models.CharField(max_length=255)),
                ('dateBirth', models.DateTimeField()),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('extNum', models.CharField(max_length=10)),
                ('personEmail', models.CharField(max_length=255)),
                ('collegeEmail', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('adminRight', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='userGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('person_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personGroupID', to='campus3.Person')),
            ],
        ),
        migrations.CreateModel(
            name='userType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameType', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='usergroup',
            name='userType_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userTypeID', to='campus3.userType'),
        ),
        migrations.AddField(
            model_name='parking',
            name='ID_parking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personParkingID', to='campus3.Person'),
        ),
        migrations.AddField(
            model_name='mealgroup',
            name='ID_meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personMealID', to='campus3.Person'),
        ),
        migrations.AddField(
            model_name='mealgroup',
            name='ID_mealType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mealTypeID', to='campus3.MealCardType'),
        ),
        migrations.AddField(
            model_name='building',
            name='ID_building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personBuildingID', to='campus3.Person'),
        ),
    ]
